version: '3'
services:
  api:
    build:
      dockerfile: dockerfiles/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - bucket
    environment:
      SKULD_MINIO_ENDPOINT: "${SKULD_MINIO_ENDPOINT}"
      SKULD_MINIO_ACCESS_KEY: "${SKULD_MINIO_ACCESS_KEY}"
      SKULD_MINIO_SECRET_KEY: "${SKULD_MINIO_SECRET_KEY}"
      SKULD_API_MINIO_BUCKET_NAME: "${SKULD_API_MINIO_BUCKET_NAME}"
      SKULD_API_MINIO_MODEL_NAME: "${SKULD_API_MINIO_MODEL_NAME}"
  bucket:
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: always
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: "${SKULD_MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${SKULD_MINIO_SECRET_KEY}"
  caddy:
    build:
      dockerfile: dockerfiles/Dockerfile.server
#    restart: always
    ports:
      - "80:80"
      - "443:443"
volumes:
  minio_storage:
