FROM python:3.11.5-slim
WORKDIR /skuld

COPY requirements-api.txt .
RUN pip install --default-timeout=1000 --prefer-binary --no-cache-dir -r requirements-api.txt

COPY skuld/api skuld/api
ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "skuld.api.app:app"]
